### ISSUE TITLE
Article "/2018/10/indemnisation-teletravail/"

### ISSUE THREAD

**Issue by diox** [borisschapira/borisschapira.com#171]
Salut,

Étant moi-même en télétravail ton article j'ai lu ton article avec grand intérêt! Un collègue a remarqué ce passage:

> Exemple :
Appartement de 70 m² dont 10 m² pour l’usage professionnel.
Le loyer s’élève à 370 €/mois (...)

D'après https://immobilier.lefigaro.fr/article/le-loyer-moyen-des-francais-est-de-628-euros-par-mois_6cf97d06-d1cf-11e6-b36e-ce717b784d0d/, dont les chiffres sont déjà à prendre avec des pincettes vu qu'ils viennent d'un réseau d'agences, il fallait en moyenne 668 € pour avoir à peu près cette surface (un peu moins) à Nancy ou Saint-Étienne il y a 2 ans, donc à 370 € ça me semble un peu optimiste. Est-ce que c'était tiré d'un vrai loyer ? Si non, peut-être ça vaudrait le coup de prendre un exemple un peu plus réaliste ?

**Comment by borisschapira** [comment]
C'est une excellente idée. Si tu veux faire une PR, je l'accepterai avec plaisir. Sinon je m'en occuperais dès que possible.
